### ISSUE TITLE
ValueError: f(a) and f(b) must have different signs at construct_similarity_matrix.py

### ISSUE THREAD

**Issue by biobai** [raphael-group/hierarchical-hotnet#4]
Hi 
It always shows this error when I run the cmd below.

python src/construct_similarity_matrix.py -i data/ntk.txt -o intermediate/similarity_matrix.h5 -bof intermediate/beta.txt

Traceback (most recent call last):
  File "src/construct_similarity_matrix.py", line 75, in <module>
    run(get_parser().parse_args(sys.argv[1:]))
  File "src/construct_similarity_matrix.py", line 56, in run
    beta = balanced_beta(A, args.threshold, args.num_digits)
  File "src/construct_similarity_matrix.py", line 35, in balanced_beta
    return sp.optimize.ridder(lambda beta: difference(A, beta, threshold), a=0.1**digits, b=1.0-0.1**digits, xtol=0.1**(digits+1))
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/zeros.py", line 625, in ridder
    r = _zeros._ridder(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
ValueError: f(a) and f(b) must have different signs

the test file is attached here
[ntk.txt](https://github.com/raphael-group/hierarchical-hotnet/files/3229213/ntk.txt)

**Comment by matthewreyna** [comment]
Do you also encounter this error when you run the example code?  Please try `example_commands.sh` in the `examples` folder.

**Comment by biobai** [comment]
No, the example is OK. But I don't know why my data do not fit.

**Comment by matthewreyna** [comment]
I updated this script to prevent this error.  Please pull or download the repository again and retry with your network.

**Comment by yangle293** [comment]
I also had this problem and I have to say this is not a good fix: you just give a 0.5 for beta if the optimization is crashed. It makes no sense to me.

**Comment by matthewreyna** [comment]
As described in the Hierarchical HotNet paper, this parameter selection procedure determines the locality of the random walk with restart.  It chooses the restart parameter beta so that the stationary distribution of the random walk is, on average, evenly balanced between the first-order and more distant neighbors of each vertex.  However, for some networks, this procedure may unfortunately lead to random walks that always restart (beta = 1) or never restart (beta = 0).  Therefore, in these cases, we define the random walk so that, in expectation, it restarts half of the time (beta = 0.5).
